version: "2"

run:
  modules-download-mode: readonly

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  default: none
  enable:
    # 1. This is the default enabled set of golanci

    # We should consider enabling errcheck
    # - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

    # 2. These are not part of the default set

    # Important to prevent import of certain packages
    - depguard
    # Removes unnecessary conversions
    - unconvert
    # Flag common typos
    - misspell
    # A meta-linter seen as a good replacement for golint
    - revive
    # Gocritic
    - gocritic

    # 3. We used to use these, but have now removed them

    # Use of prealloc is generally premature optimization and performance profiling should be done instead
    # https://golangci-lint.run/usage/linters/#prealloc
    # - prealloc
    # Provided by revive in a better way
    # - nakedret

  settings:
    staticcheck:
      checks:
        # Below is the default set
        - "all"
        - "-ST1000"
        - "-ST1003"
        - "-ST1016"
        - "-ST1020"
        - "-ST1021"
        - "-ST1022"
        # FIXME: this below this point is disabled for now, but we should investigate
        - "-QF1008"  # Omit embedded fields from selector expression https://staticcheck.dev/docs/checks#QF1008
        - "-QF1003"  # Convert if/else-if chain to tagged switch https://staticcheck.dev/docs/checks#QF1003
        - "-QF1009"  # Use time.Time.Equal instead of == operator https://staticcheck.dev/docs/checks#QF1009
        - "-QF1001"  # Apply De Morgan’s law https://staticcheck.dev/docs/checks#QF1001
        - "-QF1012"  # Use fmt.Fprintf(x, ...) instead of x.Write(fmt.Sprintf(...)) https://staticcheck.dev/docs/checks#QF1012
        - "-ST1005"  # Expand call to math.Pow https://staticcheck.dev/docs/checks#QF1005
        - "-QF1004"  # Use strings.ReplaceAll instead of strings.Replace with n == -1 https://staticcheck.dev/docs/checks#QF1004
    revive:
      enable-all-rules: true
      rules:
        # See https://revive.run/r
        # Below are unsorted, and we might want to review them to decide which one we want to enable
        - name: exported
          disabled: true
        - name: add-constant
          disabled: true
        - name: cognitive-complexity
          disabled: true
        - name: package-comments
          disabled: true
        - name: cyclomatic
          disabled: true
        - name: deep-exit
          disabled: true
        - name: function-length
          disabled: true
        - name: flag-parameter
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: max-control-nesting
          disabled: true
        - name: confusing-results
          disabled: true
        - name: nested-structs
          disabled: true
        - name: import-alias-naming
          disabled: true
        - name: filename-format
          disabled: true
        - name: use-any
          disabled: true
        # FIXME: we should enable these below
        - name: empty-lines
          disabled: true
        - name: unhandled-error
          disabled: true
        - name: confusing-naming
          disabled: true
        - name: unused-parameter
          disabled: true
        - name: unused-receiver
          disabled: true
        - name: import-shadowing
          disabled: true
        - name: use-errors-new
          disabled: true
        - name: argument-limit
          disabled: true
        - name: defer
          disabled: true
        - name: early-return
          disabled: true
        - name: comment-spacings
          disabled: true
        - name: function-result-limit
          disabled: true
        - name: unnecessary-stmt
          disabled: true
        - name: unchecked-type-assertion
          disabled: true
        - name: bare-return
          disabled: true
        # Below have been reviewed and disabled
        - name: line-length-limit
          # Better dealt with by formatter golines
          disabled: true
    depguard:
      rules:
        no-patent:
          # do not link in golang-lru anywhere (problematic patent)
          deny:
            - pkg: github.com/hashicorp/golang-lru/arc/v2
              desc: patented (https://github.com/hashicorp/golang-lru/blob/arc/v2.0.7/arc/arc.go#L18)
        pkg:
          # pkg files must not depend on cobra nor anything in cmd
          files:
            - '**/pkg/**/*.go'
          deny:
            - pkg: github.com/spf13/cobra
              desc: pkg must not depend on cobra
            - pkg: github.com/spf13/pflag
              desc: pkg must not depend on pflag
            - pkg: github.com/spf13/viper
              desc: pkg must not depend on viper
            - pkg: github.com/containerd/nerdctl/v2/cmd
              desc: pkg must not depend on any cmd files
    gocritic:
      disabled-checks:
        # Below are normally enabled by default, but we do not pass
        - appendAssign
        - ifElseChain
        - unslice
        - badCall
        - assignOp
        - commentFormatting
        - captLocal
        - singleCaseSwitch
        - wrapperFunc
        - elseif
        - regexpMust
      enabled-checks:
        # Below used to be enabled, but we do not pass anymore
        # - paramTypeCombine
        # - octalLiteral
        # - unnamedResult
        # - equalFold
        # - sloppyReassign
        # - emptyStringTest
        # - hugeParam
        # - appendCombine
        # - stringXbytes
        # - ptrToRefParam
        # - commentedOutCode
        # - rangeValCopy
        # - methodExprCall
        # - yodaStyleExpr
        # - typeUnparen

        # We enabled these and we pass
        - nilValReturn
        - weakCond
        - indexAlloc
        - rangeExprCopy
        - boolExprSimplify
        - commentedOutImport
        - docStub
        - emptyFallthrough
        - hexLiteral
        - typeAssertChain
        - unlabelStmt
        - builtinShadow
        - importShadow
        - initClause
        - nestingReduce
        - unnecessaryBlock
  exclusions:
    generated: disable

formatters:
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/containerd)
        - localmodule
      no-inline-comments: true
      no-prefix-comments: true
      custom-order: true
    gofumpt:
      extra-rules: true
    golines:
      max-len: 500
      tab-len: 4
      shorten-comments: true
  enable:
    - gci
    - gofmt
    # We might consider enabling the following:
    #    - gofumpt
    - golines
  exclusions:
    generated: disable
