version: "2"

run:
  issues-exit-code: 2
  modules-download-mode: readonly
  allow-parallel-runners: true
  allow-serial-runners: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  default: all
  disable:
    # These are the linters that we know we do not want
    - cyclop          # provided by revive
    - exhaustruct     # does not serve much of a purpose
    - funlen          # provided by revive
    - gocognit        # provided by revive
    - goconst         # provided by revive
    - godox           # not helpful unless we could downgrade it to warning / info
    - ginkgolinter    # no ginkgo
    - gomodguard      # we use depguard instead
    - ireturn         # too annoying with not enough value
    - lll             # provided by golines
    - nonamedreturns  # named returns are occasionally useful
    - prealloc        # premature optimization
    - promlinter      # no prometheus
    - sloglint        # no slog
    - testifylint     # no testify
    - zerologlint     # no zerolog
  settings:
    depguard:
      rules:
        main:
          files:
            - $all
          allow:
            - $gostd
            - github.com/containerd/nerdctl/mod/tigron
            - github.com/creack/pty
            - golang.org/x/sync
            - golang.org/x/term
            - go.uber.org/goleak
    staticcheck:
      checks:
        - all
  exclusions:
    generated: disable

formatters:
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/containerd)
        - localmodule
      no-inline-comments: true
      no-prefix-comments: true
      custom-order: true
    gofumpt:
      extra-rules: true
    golines:
      max-len: 120
      tab-len: 4
      shorten-comments: true
  enable:
    - gci
    - gofumpt
    - golines
  exclusions:
    generated: disable
