# This job runs any subsidiary linter not part of golangci (shell, yaml, etc)
name: job-lint-other

on:
  workflow_call:
    inputs:
      timeout:
        required: true
        type: number
      runner:
        required: true
        type: string

env:
  GOTOOLCHAIN: local

jobs:
  lint-other:
    name: "yaml | shell"
    timeout-minutes: ${{ inputs.timeout }}
    runs-on: ${{ inputs.runner }}
    defaults:
      run:
        shell: bash

    steps:
      - name: "Init: checkout"
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
        with:
          fetch-depth: 1

      - name: "Run: yaml"
        run: |
          make lint-yaml

      - name: "Run: shell"
        run: |
          make lint-shell
