name: project

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:

env:
  GOTOOLCHAIN: local

jobs:
  project:
    name: checks
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          path: src/github.com/containerd/nerdctl
          fetch-depth: 100
      - name: "Install go"
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b  # v5.4.0
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
          cache-dependency-path: src/github.com/containerd/nerdctl
      - uses: containerd/project-checks@d7751f3c375b8fe4a84c02a068184ee4c1f59bc4  # v1.2.2
        with:
          working-directory: src/github.com/containerd/nerdctl
          repo-access-token: ${{ secrets.GITHUB_TOKEN }}
          # go-licenses-ignore is set because go-licenses cannot detect the license of the following package:
          # * go-base36: Apache-2.0 OR MIT (https://github.com/multiformats/go-base36/blob/master/LICENSE.md)
          #
          # The list of the CNCF-approved licenses can be found here:
          # https://github.com/cncf/foundation/blob/main/allowed-third-party-license-policy.md
          go-licenses-ignore: |
            github.com/multiformats/go-base36
